; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:fluidman-esp32-s3-4r2-nofs]
platform = espressif32
; update platform to Arduino 3.1.1 for support of RMT module, latest ESP-IDF
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = dwarfnova-esp32-s3-4r2-nofs
framework = arduino
extra_scripts = pre:extra_script.py
;upload_port = COM6
;upload_speed = 2000000
;monitor_port = COM4
monitor_speed = 115200
;monitor_raw = yes
monitor_filters = esp32_exception_decoder
debug_tool = esp-builtin
;debug_tool = esp-bridge
;debug_init_break = tbreak setup
debug_speed = 15000
debug_build_flags = -g -ggdb -std=gnu++20
;debug_build_flags = -fpermissive -Wno-deprecated-declarations -Wno-deprecated-enum-enum-conversion -O3
;debug_extra_cmds = 
;	set remotetimeout 5000
;	show remotetimeout
;build_type = debug
build_type = debug
build_flags =
	'-D USE_MODBUS_RTU=1'
	'-D MODBUS_DISABLE_TCP=1'
	'-D ARDUINO_USB_MODE=1'
	'-D ARDUINO_USB_CDC_ON_BOOT=1'
	'-D CONFIG_FREERTOS_HZ=1000'
	'-D CORE_DEBUG_LEVEL=1'
	'-D CONFIG_LOG_DEFAULT=1'
	'-D WIFI_SSID="Bushwood"'
	'-D WIFI_PASS="BlueHouse"'
	'-D CONFIG_COMPILER_OPTIMIZATION_PERF=y'
	'-D WIFI_SSID2="ClockworkAngels"'
	'-D WIFI_PASS2="rush2112"'
	;'-D CONFIG_ESP_TASK_WDT_TIMEOUT_S=10'
	;'-D WIFI_SSID2="unitA"'
	;'-D WIFI_PASS2="4108avea"'
;	'-D USE_HSPI_PORT=1'
lib_ldf_mode = deep
lib_deps = 
	emelianov/modbus-esp8266@^4.1.0
