#pragma once
#include <cstdint>
#include "globals.h"
#include "pins.h"
// Modbus Register Map - auto generated from ModbusRegisters.xlsx by processmap.py
//#######  DO NOT EDIT THIS FILE - IT WILL BE OVERWRITTEN  #######

// Modbus Coils
typedef enum {
    ERROR = 1,
    RESET = 2,
    STATLED = 3,
    ERRLED = 4,
    BOOST_REG = 10,
    SAMPLE_REG = 11,
    PINCH_FULL = 12,
    PINCH_SOFT = 13,
    NOZZLE1 = 14,
    NOZZLE1_SELECT = 15,
    NOZZLE2 = 16,
    NOZZLE2_SELECT = 17,
    WASTE_CATCHER = 18,
    DRIP_TRAY = 19,
    SAMPLE_STATION = 20,
    FWUPDSTART = 100,
    FWUPDEND = 101,
    FWUPDABORT = 102,
} mod_coils_t;

// Modbus Discrete Inputs (contacts)
typedef enum {
    INERROR = 1,
    BOOTSW = 2,
    VACUUM_SWITCH = 10,
    FANALERT = 11,
} mod_contacts_t;

// Modbus Holding Registers
typedef enum {
    CONFIG = 1,
    SERIALNUM_PROG = 2,
    REGBAUD = 3,
    LEDCOLOR = 4,
    LEDBRIGHTPCT = 6,
    FAN_RPM_SET1 = 10,
    FAN_RPM_SET2 = 11,
    CTLMODE = 12,
    TEMPTARGET = 13,
    FANPID_INTERVAL = 15,
    FANPID_KP = 16,
    FANPID_KI = 18,
    FANPID_KD = 20,
    PRESSURE_SET_ANALOG = 22,
    PRESSURE_SET_DIGITAL = 24,
    FWSIZE = 100,
    FWCHECKSUM = 102,
    FWDATA = 200,
} mod_holdregs_t;

// Modbus Input Registers
typedef enum {
    BOARDID = 1,
    FWVER = 2,
    SERIALNUM = 3,
    STATUSREG = 4,
    ERRNUM = 5,
    FAN_RPM_MON1 = 10,
    FAN_RPM_MON2 = 11,
    WIFI_RSSI = 12,
    BOARD_TEMP = 13,
    PRESSURE_MON_ANALOG = 15,
    PRESSURE_MON_DIGITAL = 17,
    OMEGA_PRESSURE = 19,
    LASER_TEMP = 21,
    MAN_TEMP = 23,
    FWUPDSTATE = 100,
    FWUPDERR = 101,
    FWUPDPERCENT = 102,
} mod_inregs_t;

// prototypes for the GPIO initialization
void modGpioInit(void);

// prototypes for the Alicat serial presssure regulator initialization
void modAliRegInit(void);

// prototypes for the DAC min/max values
void modDacMinMax(void);

// prototypes for the ADC min/max values
void modAdcMinMax(void);

//####################################################################
