# script to process the xlsx data file for the modbus registers and create the enum include file for the modbus registers
# this requires a pre action for platformio to run this script before building the project
# pre action: python src/processmap.py
import pandas as pd

excel_file = './config/modbusmap.xlsx'
df = pd.read_excel(excel_file)

# fill in data from spanned cells in the ModbusType column using fillna
#df['ModbusType'].fillna(method='ffill', axis=0, inplace=True) # this method has been depracated
df['ModbusType'] = df['ModbusType'].ffill() # use ffill() instead
# fill in the address and channel empty cells with 0's
df['CtlAddr'] = df['CtlAddr'].fillna(value=0)   # removed inplace=True due to warnings about chained assignment
df['CtlChan'] = df['CtlChan'].fillna(value=0)

# create the enum include file
enum_file = 'include/modbusmap_gen.h'
with open(enum_file, 'w') as f:
    f.write('#pragma once\n')
    f.write('#include <cstdint>\n')
    f.write('#include "globals.h"\n')
    f.write('#include "pins.h"\n')
    f.write('// Modbus Register Map - auto generated from ModbusRegisters.xlsx by processmap.py\n')
    f.write('//#######  DO NOT EDIT THIS FILE - IT WILL BE OVERWRITTEN  #######\n\n')
    # first process the coils
    f.write('// Modbus Coils\n')
    f.write('typedef enum {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'COIL'):
            f.write(f'    {row["RegisterName"]} = {int(row["RegisterNumber"])},\n')
    f.write('} mod_coils_t;\n\n')

    # next process the discrete inputs (contacts)
    f.write('// Modbus Discrete Inputs (contacts)\n')
    f.write('typedef enum {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'CONTACT'):
            f.write(f'    {row["RegisterName"]} = {int(row["RegisterNumber"])},\n')
    f.write('} mod_contacts_t;\n\n')

    # next process the holding registers
    f.write('// Modbus Holding Registers\n')
    f.write('typedef enum {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'HOLDREG'):
            f.write(f'    {row["RegisterName"]} = {int(row["RegisterNumber"])},\n')
    f.write('} mod_holdregs_t;\n\n')

    # next process the input registers
    f.write('// Modbus Input Registers\n')
    f.write('typedef enum {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'INREG'):
            f.write(f'    {row["RegisterName"]} = {int(row["RegisterNumber"])},\n')
    f.write('} mod_inregs_t;\n\n')
    f.write('// prototypes for the GPIO initialization\n')
    f.write('void modGpioInit(void);\n\n')
    #f.write('// prototypes for the PWM initialization\n')
    #f.write('void modPwmInit(void);\n\n')
    #f.write('// prototypes for the Sensirion SFx6000 RS485 serial controller/meter initialization\n')
    #f.write('void modFlowInit(void);\n\n')
    #f.write('// prototypes for the Alicat serial controller/meter initialization\n')
    #f.write('void modAFlowInit(void);\n\n')
    f.write('// prototypes for the Alicat serial presssure regulator initialization\n')
    f.write('void modAliRegInit(void);\n\n')
    f.write('// prototypes for the DAC min/max values\n')
    f.write('void modDacMinMax(void);\n\n')
    f.write('// prototypes for the ADC min/max values\n')
    f.write('void modAdcMinMax(void);\n\n')
    #f.write('void modAdcIntMinMax(void);\n\n')
    #f.write('// prototypes for the RTD Rref/offset values\n')
    #f.write('void modRtdCal(void);\n\n')
    f.write('//####################################################################\n')
    f.close()

# create the map cpp file
map_file = 'src/modbusmap_gen.cpp'
with open(map_file, 'w') as f:
    f.write('#include <cstdint>\n')
    f.write('#include "dac.h"\n')
    f.write('#include "adc.h"\n')
    f.write('#include "modbusmap.h"\n')
    f.write('#include "modbusmap_gen.h"\n')
    f.write('// Modbus Register Map - auto generated from ModbusRegisters.xlsx by processmap.py\n')
    f.write('//#######  DO NOT EDIT THIS FILE - IT WILL BE OVERWRITTEN  #######\n\n')
    # first process the coils
    f.write('// Modbus Coils\n')
    f.write('const bitresource_t coilmap[] = {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'COIL'):
            # handle variables as a special case to copy the variable pointer into the address field of the map
            if(row['CtlDriver'] == 'BITVAR'):
                f.write(f'  {{ .num={row["RegisterNumber"]}, .name="{row["RegisterName"]}", .acc=RES_RW, .init=0, .drvr={"DRVR_" + row["CtlDriver"]}, .drvaddr=(uint32_t) &{row["CtlAddr"]}, .drvchan={int(row["CtlChan"])} }},\n')
            else:
                f.write(f'  {{ .num={row["RegisterNumber"]}, .name="{row["RegisterName"]}", .acc=RES_RW, .init=0, .drvr={"DRVR_NONE" if pd.isnull(row["CtlDriver"]) else "DRVR_" + row["CtlDriver"]}, .drvaddr={int(abs(row["CtlAddr"]))}, .drvchan={int(row["CtlChan"])} }},\n')
    f.write('  { .num=0, .name=NULL, .acc=RES_RO, .init=0, .drvr=DRVR_NONE, .drvaddr=0,  .drvchan=0 }\n')
    f.write('};\n\n')


    # next process the discrete inputs (contacts)
    f.write('// Modbus Discrete Inputs (contacts)\n')
    f.write('const bitresource_t contmap[] = {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'CONTACT'):
            # handle variables as a special case to copy the variable pointer into the address field of the map
            if(row['CtlDriver'] == 'BITVAR'):
                f.write(f'  {{ .num={row["RegisterNumber"]}, .name="{row["RegisterName"]}", .acc=RES_RO, .init=0, .drvr={"DRVR_" + row["CtlDriver"]}, .drvaddr=(uint32_t) &{row["CtlAddr"]}, .drvchan={int(row["CtlChan"])} }},\n')
            else:
                f.write(f'  {{ .num={row["RegisterNumber"]}, .name="{row["RegisterName"]}", .acc=RES_RO, .init=0, .drvr={"DRVR_NONE" if pd.isnull(row["CtlDriver"]) else "DRVR_" + row["CtlDriver"]}, .drvaddr={int(abs(row["CtlAddr"]))}, .drvchan={int(row["CtlChan"])} }},\n')
    f.write('  { .num=0, .name=NULL, .acc=RES_RO, .init=0, .drvr=DRVR_NONE, .drvaddr=0,  .drvchan=0 }\n')
    f.write('};\n\n')

    # next process the holding registers
    f.write('// Modbus Holding Registers\n')
    f.write('const wordresource_t holdregmap[] = {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'HOLDREG'):
            # handle variables as a special case to copy the variable pointer into the address field of the map
            if(row['CtlDriver'] == 'VAR'):
                f.write(f'  {{ .num={row["RegisterNumber"]}, .name="{row["RegisterName"]}", .acc=RES_RW, .init=0, .fmt=\'{row["Format"]}\', .len={int(row["NumBits"]/8)}, .drvr={"DRVR_" + row["CtlDriver"]}, .drvaddr=(uint32_t) &{row["CtlAddr"]}, .drvchan={abs(int(row["CtlChan"]))} }},\n')
            else:
                f.write(f'  {{ .num={row["RegisterNumber"]}, .name="{row["RegisterName"]}", .acc=RES_RW, .init=0, .fmt=\'{row["Format"]}\', .len={int(row["NumBits"]/8)}, .drvr={"DRVR_NONE" if pd.isnull(row["CtlDriver"]) else "DRVR_" + row["CtlDriver"]}, .drvaddr={int(row["CtlAddr"])}, .drvchan={abs(int(row["CtlChan"]))} }},\n')
    f.write('  { .num=0, .name=NULL, .acc=RES_RO, .init=0, .fmt=0, .len=0, .drvr=DRVR_NONE, .drvaddr=0,  .drvchan=0 }\n')
    f.write('};\n\n')

    # next process the input registers
    f.write('// Modbus Input Registers\n')
    f.write('const wordresource_t inregmap[] = {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'INREG'):
            # handle variables as a special case to copy the variable pointer into the address field of the map
            if(row['CtlDriver'] == 'VAR'):
                f.write(f'  {{ .num={row["RegisterNumber"]}, .name="{row["RegisterName"]}", .acc=RES_RO, .init=0, .fmt=\'{row["Format"]}\', .len={int(row["NumBits"]/8)}, .drvr={"DRVR_" + row["CtlDriver"]}, .drvaddr=(uint32_t) &{row["CtlAddr"]}, .drvchan={abs(int(row["CtlChan"]))} }},\n')
            else:
                f.write(f'  {{ .num={row["RegisterNumber"]}, .name="{row["RegisterName"]}", .acc=RES_RO, .init=0, .fmt=\'{row["Format"]}\', .len={int(row["NumBits"]/8)}, .drvr={"DRVR_NONE" if pd.isnull(row["CtlDriver"]) else "DRVR_" + row["CtlDriver"]}, .drvaddr={int(row["CtlAddr"])}, .drvchan={int(row["CtlChan"])} }},\n')
    f.write('  { .num=0, .name=NULL, .acc=RES_RO, .init=0, .fmt=0, .len=0, .drvr=DRVR_NONE, .drvaddr=0,  .drvchan=0 }\n')
    f.write('};\n\n')

    # create the initialization code for the GPIOs referenced in the file
    f.write('//--------------------------------------------------------------------\n')
    f.write('// GPIO Initialization\n')
    f.write('//--------------------------------------------------------------------\n')
    f.write('void modGpioInit(void) {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'COIL' or row['ModbusType'] == 'CONTACT'):
            if(row['CtlDriver'] == 'GPIO'):
                f.write(f'  pinGPIO[{int(row["CtlChan"])}].init(GPIO_MODE_{"OUTPUT" if(row["ModbusType"]=="COIL") else "INPUT"}, GPIO_NUM_{int(abs(row["CtlAddr"]))}{", true" if(row["CtlAddr"] < 0) else ""});  // GPIOtab[{int(row["CtlChan"])}] -> Pin{int(abs(row["CtlAddr"]))}{" (active_low)" if(row["CtlAddr"] < 0) else ""}\n')
    f.write('} // end of GPIO initialization \n')
    # create the initialization code for the PWMENs referenced in the file
    #f.write('//--------------------------------------------------------------------\n')
    #f.write('// PWM Initialization\n')
    #f.write('//--------------------------------------------------------------------\n')
    #f.write('void modPwmInit(void) {\n')
    #for index, row in df.iterrows():
    #    if(row['ModbusType'] == 'COIL'):
    #        if(row['CtlDriver'] == 'PWMEN'):
    #            f.write(f'  pwm[{int(row["CtlChan"])}].init({int(row["CtlChan"])}, {int(row["CtlAddr"])});  // GPIO_NUM_{int(row["CtlAddr"])} -> PWMch{int(row["CtlChan"])}\n') 
    #f.write('} // end of PWM initialization \n')
    f.write('//--------------------------------------------------------------------\n')
    f.write('// Alicat RS485 serial pressure regulator Initialization\n')
    f.write('//--------------------------------------------------------------------\n')
    f.write('void modAliRegInit(void) {\n')
    f.write('  // initialize the address of any Alicat flow meters defined in the modbus spreadsheet (in HOLDREG section)\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'HOLDREG'):
            if(row['CtlDriver'] == 'ALIREG'):
                f.write(f'  areg[{int(row["CtlAddr"])}].Init({int(row["CtlAddr"])});  // Device addr {int(row["CtlAddr"])} is a regulator\n')
    f.write('} // end of Alicat Flow controller/meter initialization \n')
    f.write('//--------------------------------------------------------------------\n')
    f.write('// DAC min/max values\n')
    f.write('//--------------------------------------------------------------------\n')
    f.write('void modDacMinMax(void) {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'HOLDREG'):
            if(row['CtlDriver'] == 'DAC'):
                f.write(f'  dac.SetMax(static_cast<CHANNEL_SELECT>({int(row["CtlChan"])}), {float(row["CtlMaxVal"])});\n') 
                f.write(f'  dac.SetMin(static_cast<CHANNEL_SELECT>({int(row["CtlChan"])}), {float(row["CtlMinVal"])});\n') 
            if(row['CtlDriver'] == 'MCPDAC'):
                f.write(f'  dac.SetMax({float(row["CtlMaxVal"])});\n') 
                f.write(f'  dac.SetMin({float(row["CtlMinVal"])});\n') 
    f.write('} // end of DAC min/max initialization \n')
    f.write('//--------------------------------------------------------------------\n')
    f.write('// ADC min/max values\n')
    f.write('//--------------------------------------------------------------------\n')
    f.write('void modAdcMinMax(void) {\n')
    for index, row in df.iterrows():
        if(row['ModbusType'] == 'INREG'):
            if(row['CtlDriver'] == 'ADC'):
                if(not (pd.isnull(row["CtlMaxVal"]))):
                    f.write(f'  adc[{int(row["CtlAddr"])}].SetMax({abs(int(row["CtlChan"]))}, {float(row["CtlMaxVal"])});\n')
                    f.write(f'  adc[{int(row["CtlAddr"])}].SetMin({abs(int(row["CtlChan"]))}, {float(row["CtlMinVal"])});\n') 
    f.write('} // end of SPI ADC min/max initialization \n')
    #f.write('// Internal ESP32 ADC min/max values\n')
    #f.write('void modAdcIntMinMax(void) {\n')
    #for index, row in df.iterrows():
    #    if(row['ModbusType'] == 'INREG'):
    #        if(row['CtlDriver'] == 'ADC'):
    #            if(not (pd.isnull(row["CtlMaxVal"]))):
    #                f.write(f'  adcint.SetPin(static_cast<adcintchan_t>({abs(int(row["CtlChan"]))}), GPIO_NUM_{int(abs(row["CtlAddr"]))});\n')
    #                f.write(f'  adcint.SetMax(static_cast<adcintchan_t>({abs(int(row["CtlChan"]))}), {float(row["CtlMaxVal"])});\n')
    #                f.write(f'  adcint.SetMin(static_cast<adcintchan_t>({abs(int(row["CtlChan"]))}), {float(row["CtlMinVal"])});\n') 
    #f.write('} // end of internal ADC min/max initialization \n')
    #f.write('//--------------------------------------------------------------------\n')
    #f.write('// RTD calibration Rref/offset values\n')
    #f.write('//--------------------------------------------------------------------\n')
    #f.write('void modRtdCal(void) {\n')
    #for index, row in df.iterrows():
    #    if(row['ModbusType'] == 'INREG'):
    #        if(row['CtlDriver'] == 'SPIRTD'):
    #            if(not (pd.isnull(row["CtlMaxVal"]))):
    #                f.write(f'  rtd[{int(row["CtlAddr"])}].setRefRes({float(row["CtlMaxVal"])});\n')
    #                f.write(f'  rtd[{int(row["CtlAddr"])}].setCalOffset({float(row["CtlMinVal"])});\n')
    #f.write('} // end of ADC min/max initialization \n')
    f.write('//####################################################################\n')
    f.close()
