#include <cstdint>
#include "dac.h"
#include "adc.h"
#include "modbusmap.h"
#include "modbusmap_gen.h"
// Modbus Register Map - auto generated from ModbusRegisters.xlsx by processmap.py
//#######  DO NOT EDIT THIS FILE - IT WILL BE OVERWRITTEN  #######

// Modbus Coils
const bitresource_t coilmap[] = {
  { .num=1, .name="ERROR", .acc=RES_RW, .init=0, .drvr=DRVR_BITVAR, .drvaddr=(uint32_t) &boardctl, .drvchan=0 },
  { .num=2, .name="RESET", .acc=RES_RW, .init=0, .drvr=DRVR_BITVAR, .drvaddr=(uint32_t) &boardctl, .drvchan=1 },
  { .num=3, .name="STATLED", .acc=RES_RW, .init=0, .drvr=DRVR_NONE, .drvaddr=0, .drvchan=0 },
  { .num=4, .name="ERRLED", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=7, .drvchan=1 },
  { .num=10, .name="BOOST_REG", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=11, .drvchan=2 },
  { .num=11, .name="SAMPLE_REG", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=12, .drvchan=3 },
  { .num=12, .name="PINCH_FULL", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=13, .drvchan=4 },
  { .num=13, .name="PINCH_SOFT", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=14, .drvchan=5 },
  { .num=14, .name="NOZZLE1", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=35, .drvchan=6 },
  { .num=15, .name="NOZZLE1_SELECT", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=36, .drvchan=7 },
  { .num=16, .name="NOZZLE2", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=37, .drvchan=8 },
  { .num=17, .name="NOZZLE2_SELECT", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=38, .drvchan=9 },
  { .num=18, .name="WASTE_CATCHER", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=39, .drvchan=10 },
  { .num=19, .name="DROP_TRAY", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=40, .drvchan=11 },
  { .num=20, .name="SAMPLE_STATION", .acc=RES_RW, .init=0, .drvr=DRVR_GPIO, .drvaddr=41, .drvchan=12 },
  { .num=0, .name=NULL, .acc=RES_RO, .init=0, .drvr=DRVR_NONE, .drvaddr=0,  .drvchan=0 }
};

// Modbus Discrete Inputs (contacts)
const bitresource_t contmap[] = {
  { .num=1, .name="INERROR", .acc=RES_RO, .init=0, .drvr=DRVR_BITVAR, .drvaddr=(uint32_t) &boardstat, .drvchan=0 },
  { .num=2, .name="BOOTSW", .acc=RES_RO, .init=0, .drvr=DRVR_GPIO, .drvaddr=0, .drvchan=0 },
  { .num=10, .name="VACUUM_SWITCH", .acc=RES_RO, .init=0, .drvr=DRVR_GPIO, .drvaddr=9, .drvchan=13 },
  { .num=11, .name="FANALERT", .acc=RES_RO, .init=0, .drvr=DRVR_GPIO, .drvaddr=10, .drvchan=14 },
  { .num=0, .name=NULL, .acc=RES_RO, .init=0, .drvr=DRVR_NONE, .drvaddr=0,  .drvchan=0 }
};

// Modbus Holding Registers
const wordresource_t holdregmap[] = {
  { .num=1, .name="CONFIG", .acc=RES_RW, .init=0, .fmt='u', .len=2, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &boardctl, .drvchan=0 },
  { .num=2, .name="SERIALNUM_PROG", .acc=RES_RW, .init=0, .fmt='u', .len=2, .drvr=DRVR_FLASH, .drvaddr=0, .drvchan=0 },
  { .num=3, .name="REGBAUD", .acc=RES_RW, .init=0, .fmt='u', .len=2, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &regbaud, .drvchan=0 },
  { .num=4, .name="LEDCOLOR", .acc=RES_RW, .init=0, .fmt='u', .len=4, .drvr=DRVR_SERLED, .drvaddr=0, .drvchan=0 },
  { .num=6, .name="LEDBRIGHTPCT", .acc=RES_RW, .init=0, .fmt='u', .len=2, .drvr=DRVR_SERLED, .drvaddr=1, .drvchan=0 },
  { .num=10, .name="FAN_RPM_SET1", .acc=RES_RW, .init=0, .fmt='u', .len=2, .drvr=DRVR_FAN, .drvaddr=0, .drvchan=0 },
  { .num=11, .name="FAN_RPM_SET2", .acc=RES_RW, .init=0, .fmt='u', .len=2, .drvr=DRVR_FAN, .drvaddr=0, .drvchan=1 },
  { .num=12, .name="CTLMODE", .acc=RES_RW, .init=0, .fmt='u', .len=2, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &ctlmode, .drvchan=0 },
  { .num=13, .name="TEMPTARGET", .acc=RES_RW, .init=0, .fmt='f', .len=4, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &temp_target, .drvchan=0 },
  { .num=15, .name="FANPID_INTERVAL", .acc=RES_RW, .init=0, .fmt='u', .len=2, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &fan_interval, .drvchan=0 },
  { .num=16, .name="FANPID_KP", .acc=RES_RW, .init=0, .fmt='f', .len=4, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &fan_kp, .drvchan=0 },
  { .num=18, .name="FANPID_KI", .acc=RES_RW, .init=0, .fmt='f', .len=4, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &fan_ki, .drvchan=0 },
  { .num=20, .name="FANPID_KD", .acc=RES_RW, .init=0, .fmt='f', .len=4, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &fan_kd, .drvchan=0 },
  { .num=22, .name="PRESSURE_SET_ANALOG", .acc=RES_RW, .init=0, .fmt='f', .len=4, .drvr=DRVR_DAC, .drvaddr=0, .drvchan=0 },
  { .num=24, .name="PRESSURE_SET_DIGITAL", .acc=RES_RW, .init=0, .fmt='f', .len=4, .drvr=DRVR_ALIREG, .drvaddr=0, .drvchan=1 },
  { .num=0, .name=NULL, .acc=RES_RO, .init=0, .fmt=0, .len=0, .drvr=DRVR_NONE, .drvaddr=0,  .drvchan=0 }
};

// Modbus Input Registers
const wordresource_t inregmap[] = {
  { .num=1, .name="BOARDID", .acc=RES_RO, .init=0, .fmt='u', .len=2, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &boardinfo, .drvchan=0 },
  { .num=2, .name="FWVER", .acc=RES_RO, .init=0, .fmt='u', .len=2, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &fwinfo, .drvchan=0 },
  { .num=3, .name="SERIALNUM", .acc=RES_RO, .init=0, .fmt='u', .len=2, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &serialno, .drvchan=0 },
  { .num=4, .name="STATUSREG", .acc=RES_RO, .init=0, .fmt='u', .len=2, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &boardstat, .drvchan=0 },
  { .num=5, .name="ERRNUM", .acc=RES_RO, .init=0, .fmt='u', .len=1, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &faulterr, .drvchan=0 },
  { .num=10, .name="FAN_RPM_MON1", .acc=RES_RO, .init=0, .fmt='u', .len=2, .drvr=DRVR_FAN, .drvaddr=1, .drvchan=0 },
  { .num=11, .name="FAN_RPM_MON2", .acc=RES_RO, .init=0, .fmt='u', .len=2, .drvr=DRVR_FAN, .drvaddr=1, .drvchan=1 },
  { .num=12, .name="WIFI_RSSI", .acc=RES_RO, .init=0, .fmt='d', .len=2, .drvr=DRVR_VAR, .drvaddr=(uint32_t) &wifirssi, .drvchan=0 },
  { .num=13, .name="BOARD_TEMP", .acc=RES_RO, .init=0, .fmt='f', .len=4, .drvr=DRVR_TEMP, .drvaddr=0, .drvchan=0 },
  { .num=15, .name="PRESSURE_MON_ANALOG", .acc=RES_RO, .init=0, .fmt='f', .len=4, .drvr=DRVR_ADC, .drvaddr=0, .drvchan=0 },
  { .num=17, .name="PRESSURE_MON_DIGITAL", .acc=RES_RO, .init=0, .fmt='f', .len=4, .drvr=DRVR_ALIREG, .drvaddr=0, .drvchan=0 },
  { .num=19, .name="OMEGA_PRESSURE", .acc=RES_RO, .init=0, .fmt='f', .len=4, .drvr=DRVR_ADC, .drvaddr=0, .drvchan=1 },
  { .num=21, .name="LASER_TEMP", .acc=RES_RO, .init=0, .fmt='f', .len=4, .drvr=DRVR_ADC, .drvaddr=0, .drvchan=2 },
  { .num=0, .name=NULL, .acc=RES_RO, .init=0, .fmt=0, .len=0, .drvr=DRVR_NONE, .drvaddr=0,  .drvchan=0 }
};

//--------------------------------------------------------------------
// GPIO Initialization
//--------------------------------------------------------------------
void modGpioInit(void) {
  pinGPIO[1].init(GPIO_MODE_OUTPUT, GPIO_NUM_7, true);  // GPIOtab[1] -> Pin7 (active_low)
  pinGPIO[2].init(GPIO_MODE_OUTPUT, GPIO_NUM_11);  // GPIOtab[2] -> Pin11
  pinGPIO[3].init(GPIO_MODE_OUTPUT, GPIO_NUM_12);  // GPIOtab[3] -> Pin12
  pinGPIO[4].init(GPIO_MODE_OUTPUT, GPIO_NUM_13);  // GPIOtab[4] -> Pin13
  pinGPIO[5].init(GPIO_MODE_OUTPUT, GPIO_NUM_14);  // GPIOtab[5] -> Pin14
  pinGPIO[6].init(GPIO_MODE_OUTPUT, GPIO_NUM_35);  // GPIOtab[6] -> Pin35
  pinGPIO[7].init(GPIO_MODE_OUTPUT, GPIO_NUM_36);  // GPIOtab[7] -> Pin36
  pinGPIO[8].init(GPIO_MODE_OUTPUT, GPIO_NUM_37);  // GPIOtab[8] -> Pin37
  pinGPIO[9].init(GPIO_MODE_OUTPUT, GPIO_NUM_38);  // GPIOtab[9] -> Pin38
  pinGPIO[10].init(GPIO_MODE_OUTPUT, GPIO_NUM_39);  // GPIOtab[10] -> Pin39
  pinGPIO[11].init(GPIO_MODE_OUTPUT, GPIO_NUM_40);  // GPIOtab[11] -> Pin40
  pinGPIO[12].init(GPIO_MODE_OUTPUT, GPIO_NUM_41);  // GPIOtab[12] -> Pin41
  pinGPIO[0].init(GPIO_MODE_INPUT, GPIO_NUM_0);  // GPIOtab[0] -> Pin0
  pinGPIO[13].init(GPIO_MODE_INPUT, GPIO_NUM_9, true);  // GPIOtab[13] -> Pin9 (active_low)
  pinGPIO[14].init(GPIO_MODE_INPUT, GPIO_NUM_10, true);  // GPIOtab[14] -> Pin10 (active_low)
} // end of GPIO initialization 
//--------------------------------------------------------------------
// Alicat RS485 serial pressure regulator Initialization
//--------------------------------------------------------------------
void modAliRegInit(void) {
  // initialize the address of any Alicat flow meters defined in the modbus spreadsheet (in HOLDREG section)
  areg[0].Init(0);  // Device addr 0 is a regulator
} // end of Alicat Flow controller/meter initialization 
//--------------------------------------------------------------------
// DAC min/max values
//--------------------------------------------------------------------
void modDacMinMax(void) {
  dac.SetMax(static_cast<CHANNEL_SELECT>(0), 45.0);
  dac.SetMin(static_cast<CHANNEL_SELECT>(0), 0.0);
} // end of DAC min/max initialization 
//--------------------------------------------------------------------
// ADC min/max values
//--------------------------------------------------------------------
void modAdcMinMax(void) {
  adc[0].SetMax(0, 5.49);
  adc[0].SetMin(0, -5.49);
  adc[0].SetMax(1, 1000.0);
  adc[0].SetMin(1, 0.0);
  adc[0].SetMax(2, 104.498);
  adc[0].SetMin(2, -122.648);
} // end of SPI ADC min/max initialization 
//####################################################################
